"""Add last_reordered_at to Inventory

Revision ID: 01947c7e5701
Revises: 5943fd6ccdae
Create Date: 2024-10-04 14:36:50.700041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01947c7e5701'
down_revision = '5943fd6ccdae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reordered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('last_reordered_at')

    # ### end Alembic commands ###
