"""Add customer_name and sale_date to Sale model

Revision ID: 429445e0cd6c
Revises: bbd211877e38
Create Date: 2024-09-23 13:58:49.625282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429445e0cd6c'
down_revision = 'bbd211877e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
