"""Add price column to Product model

Revision ID: 460113dae3b8
Revises: d2bff41d9ad0
Create Date: 2024-09-20 20:26:31.564996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460113dae3b8'
down_revision = 'd2bff41d9ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
