"""Fixed Supplier model import and relationship issues

Revision ID: c71ed80cf844
Revises: ec56c96e30c1
Create Date: 2024-09-25 22:23:07.413581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71ed80cf844'
down_revision = 'ec56c96e30c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('contact_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_info', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
