from setuptools import setup, find_packages

setup(
    name="smart_inventory_system",
    version="1.0.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "alembic==1.13.2",
        "aniso8601==9.0.1",
        "attrs==25.3.0",
        "blinker==1.8.2",
        "click==8.1.7",
        "colorama==0.4.6",
        "Flask==3.0.3",
        "Flask-Cors==5.0.0",
        "Flask-JWT-Extended==4.6.0",
        "Flask-Login==0.6.3",
        "flask-marshmallow==1.2.1",
        "Flask-Migrate==4.0.7",
        "Flask-RESTful==0.3.10",
        "flask-restx==1.3.0",
        "Flask-SQLAlchemy==3.1.1",
        "greenlet==3.1.0",
        "gunicorn==23.0.0",
        "importlib_resources==6.5.2",
        "itsdangerous==2.2.0",
        "Jinja2==3.1.4",
        "jsonschema==4.23.0",
        "jsonschema-specifications==2024.10.1",
        "Mako==1.3.5",
        "MarkupSafe==2.1.5",
        "marshmallow==3.22.0",
        "marshmallow-sqlalchemy==1.1.0",
        "packaging==24.1",
        "passlib==1.7.4",
        "psycopg2-binary==2.9.9",
        "PyJWT==2.9.0",
        "python-dotenv==1.0.1",
        "pytz==2024.2",
        "referencing==0.36.2",
        "rpds-py==0.23.1",
        "six==1.16.0",
        "SQLAlchemy==2.0.35",
        "typing_extensions==4.12.2",
        "Werkzeug==3.0.4",
    ],
    entry_points={
        "console_scripts": [
            "smart-inventory=manage:main",
        ],
    },
    python_requires=">=3.9",
    author="Maria Fe Fischer",
    author_email="afefischer@gmail.com",
    description="A smart inventory management system for businesses",
    keywords="inventory, management, business",
    url="https://github.com/yourusername/smart-inventory-system",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
)
