"""Add reorder_point to Product model

Revision ID: 2e4e388a6f63
Revises: e81adf445be0
Create Date: 2024-09-23 13:30:22.165798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4e388a6f63'
down_revision = 'e81adf445be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reorder_point', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('reorder_point')

    # ### end Alembic commands ###
